spring:
  datasource:
    url: jdbc:mysql://${MYSQL_DB_URL}:3306/legalconsultation?serverTimezone=Europe/Bucharest&characterEncoding=UTF-8
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true
    properties.hibernate.dialect.storage_engine: innodb
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  multipart:
    maxFileSize: 20MB
    maxRequestSize: 30MB
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
  mvc:
    locale: ro
  cache:
    cache-names: users
app:
  jwtSecret: ORy9HWgKoZPAs50ECKw0
  jwtExpirationInMs: 1728000000   # two days expiration time, can be extended
  signupurl: 'http://localhost:4200/authentication/sign-up'

storage:
  aws:
    region: ${AWS_REGION}
    access:
      key:
        id: ${AWS_ACCESS_ID}
        secret: ${AWS_SECRET_KEY}
    s3:
      documentBucket: ${AWS_DOCUMENT_BUCKET}
  filesystem:
    directory: ~
