version: '3.7'

services:
  database:
    container_name: postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'legalconsultation'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres-vol:/var/lib/postgresql/data
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  expert-api-prod:
    container_name: expert-consultation-api
    build:
      context: .
      dockerfile: Dockerfile-prod
      args:
        - JARNAME=expert-consultation-0.0.1-SNAPSHOT.jar
    environment:
      - MYSQL_DB_URL=mysql
      - MYSQL_DB_USERNAME=root
      - MYSQL_DB_PASSWORD=root
    ports:
      - '8080:8080'
    depends_on:
      - mysql
volumes:
  postgres-vol:
