version: '3.7'

services:
  database:
    container_name: postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'legalconsultation'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres-vol:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  postgres-vol:
